runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  #expiration: 30d
  
- url: /admin.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

env_variables:
  blog_name: GoBlogEngine
  base_domain_name: localhost:8080
  posts_per_page: 5
  feed_size: 50
  excerpt_char_length: 500
  date_format_for_editing: 2006-01-02T15:04
  date_format_short: Mon, Jan 2 2006
  date_format_full: Mon, Jan 2 2006 15:04:05 MST
  session_store_key: CHANGE_THIS_VALUE
  view_base_uri: /
  view_extension: html
  view_directory: templates
  view_caching: true
  root_template: base
  child_templates: admin/_menu

# These seem to work intermittently in testing
error_handlers:
  - file: templates/error/default.html

  - error_code: over_quota
    file: templates/error/over_quota.html

  - error_code: dos_api_denial
    file: templates/error/dos_api_denial.html

  - error_code: timeout
    file: templates/error/timeout.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^assets$